In [17]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [18]:
tabla = pd.read_csv("./Credito.csv")
tabla

      Riesgo     Historia Deuda     Avales   Ingresos
0       alto         mala  alta         no     0 a 2M
1       alto  desconocida  alta         no     2 a 5M
2   moderado  desconocida  baja         no     2 a 5M
3       alto  desconocida  baja         no     0 a 2M
4       bajo  desconocida  baja         no  más de 5M
5       bajo  desconocida  baja  adecuados  más de 5M
6       alto         mala  baja         no     0 a 2M
7   moderado         mala  baja  adecuados  más de 5M
8       bajo        buena  baja         no  más de 5M
9       bajo        buena  alta  adecuados  más de 5M
10      alto        buena  alta         no     0 a 2M
11  moderado        buena  alta         no     2 a 5M
12      bajo        buena  alta         no  más de 5M
13      alto         mala  alta         no     2 a 5M

In [3]:
for c, a in enumerate(tabla.columns):
    conversion = {v: i for i,v in enumerate(tabla[a].unique())}
    print(conversion)
    tabla.iloc[:,c] = [conversion[tabla.iloc[idx, c]] for idx in tabla.index]
tabla

{'alto': 0, 'moderado': 1, 'bajo': 2}
{'mala': 0, 'desconocida': 1, 'buena': 2}
{'alta': 0, 'baja': 1}
{'no': 0, 'adecuados': 1}
{'0 a 2M': 0, '2 a 5M': 1, 'más de 5M': 2}

   Riesgo Historia Deuda Avales Ingresos
0       0        0     0      0        0
1       0        1     0      0        1
2       1        1     1      0        1
3       0        1     1      0        0
4       2        1     1      0        2
5       2        1     1      1        2
6       0        0     1      0        0
7       1        0     1      1        2
8       2        2     1      0        2
9       2        2     0      1        2
10      0        2     0      0        0
11      1        2     0      0        1
12      2        2     0      0        2
13      0        0     0      0        1

In [4]:
tabla = pd.read_csv("./Credito.csv")
conversion=[{'alto': 2, 'moderado': 1, 'bajo': 0}, 
            {'mala': 0, 'desconocida': 1, 'buena': 2}, 
            {'alta': 1, 'baja': 0}, 
            {'no': 0, 'adecuados': 1}, 
            {'0 a 2M': 0, '2 a 5M': 1, 'más de 5M': 2}]
for c, a in enumerate(tabla.columns):
    tabla.iloc[:,c] = [conversion[c][tabla.iloc[idx, c]] for idx in tabla.index]
tabla

   Riesgo Historia Deuda Avales Ingresos
0       2        0     1      0        0
1       2        1     1      0        1
2       1        1     0      0        1
3       2        1     0      0        0
4       0        1     0      0        2
5       0        1     0      1        2
6       2        0     0      0        0
7       1        0     0      1        2
8       0        2     0      0        2
9       0        2     1      1        2
10      2        2     1      0        0
11      1        2     1      0        1
12      0        2     1      0        2
13      2        0     1      0        1

In [5]:
clf = DecisionTreeClassifier(criterion='entropy')

In [6]:
X = np.array(tabla.iloc[:, 1:], dtype=float).reshape(-1,4)
y = np.array(tabla.iloc[:,0], dtype=int).reshape(-1,1)

In [12]:
clf.fit(X, y)

DecisionTreeClassifier(criterion='entropy')

In [13]:
export_graphviz(clf, out_file='tree_credito_CART.dot', feature_names=tabla.columns[1:])

In [14]:
!dot -Tpng tree_credito_CART.dot -o tree_credito_CART.png -Gdpi=300

In [15]:
clf.score(X, y)

1.0

# **ARBOL GENERADO POR SKLEARN - ALGORITMO CART**
![Arbol_CART](./tree_credito_CART.png)

In [16]:
clf.feature_importances_

array([0.2753384 , 0.09333292, 0.        , 0.63132868])